global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using POSUNO.DataContracts;
global using POSUNO.DataContracts.Serialization;
global using POSUNO.Models;
global using POSUNO.Presentation;
global using POSUNO.Services.Caching;
global using POSUNO.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
